version: '3'

services: 
  node: 
    build: 
      context: .
    environment: 
      - NODE_ENV=development
    volumes: 
      - ./:/usr/src/react-tutorial
    command: |
      sh -c 'cd react-tutorial && yarn start'
    ports: 
      - 3000:3000
    tty: true